plugins {
    id 'com.android.application'
}

android {
    namespace 'nl.milton.budgetapp'
    compileSdk 36

    defaultConfig {
        applicationId 'nl.milton.budgetapp'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.17.0'
    implementation 'androidx.activity:activity:1.11.0'

    implementation 'androidx.room:room-runtime:2.8.4'
    annotationProcessor 'androidx.room:room-compiler:2.8.4'

    implementation 'androidx.camera:camera-core:1.6.1'
    implementation 'androidx.camera:camera-camera2:1.6.1'
    implementation 'androidx.camera:camera-lifecycle:1.6.1'
    implementation 'androidx.camera:camera-view:1.6.1'

    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
